apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksakslab-e9f0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksakslab-e9f0"
  template:
    metadata:
      labels:
        app: "aksakslab-e9f0"
    spec:
      containers:
        - name: "aksakslab-e9f0"
          image: "acrtsgaks.azurecr.io/aksakslab"
          ports:
          - containerPort: 80