apiVersion : apps/v1
kind: Deployment
metadata:
  name: "akstsgworkshop-bf47"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "akstsgworkshop-bf47"
  template:
    metadata:
      labels:
        app: "akstsgworkshop-bf47"
    spec:
      containers:
        - name: "akstsgworkshop-bf47"
          image: "acrtsgworkshop01.azurecr.io/akstsgworkshop"
          ports:
          - containerPort: 80