apiVersion: v1
kind: Service
metadata:
    name: "aksakslab-e9f0"
    labels:
        app: "aksakslab-e9f0"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksakslab-e9f0"